name: pull-request

on:
- pull_request

jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.26.x]
        platform: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    steps:
    # Checkout should always be before setup-go to ensure caching is working
    - name: checkout
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run unit tests
      run: make test

  build-test:
    strategy:
      matrix:
        go-version: [1.26.x]
        platform: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    steps:
    # Checkout should always be before setup-go to ensure caching is working
    - name: checkout
      uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Building binary
      run: make compile
